/**
 * HTML email body builder for PnP Action Store Report emails.
 */

const BRAND_GREEN = '#7CC042';
const BRAND_BG = '#f5f5f5';
const BRAND_CARD = '#ffffff';
const BRAND_TEXT = '#1a1a1a';
const BRAND_MUTED = '#737373';
const BRAND_CHARCOAL = '#32373C';

function tableStyle(): string {
  return `border-collapse:collapse;width:100%;font-family:Arial,sans-serif;font-size:13px;`;
}

function thStyle(): string {
  return `background:${BRAND_CHARCOAL};color:#fff;padding:8px 10px;text-align:left;font-weight:bold;`;
}

function tdStyle(even: boolean): string {
  return `padding:7px 10px;border-bottom:1px solid #e5e5e5;background:${even ? '#f9f9f9' : BRAND_CARD};color:${BRAND_TEXT};`;
}

function wrapper(content: string): string {
  return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="background:${BRAND_BG};color:${BRAND_TEXT};font-family:Arial,sans-serif;margin:0;padding:24px;">
  <div style="max-width:700px;margin:0 auto;background:${BRAND_CARD};border-radius:8px;padding:32px;border:1px solid #e0e0e0;">
    <div style="border-left:4px solid ${BRAND_GREEN};padding-left:16px;margin-bottom:24px;">
      <h1 style="color:${BRAND_CHARCOAL};margin:0;font-size:20px;">PnP Action Store Report</h1>
      <p style="color:${BRAND_MUTED};margin:4px 0 0;">iRam / OuterJoin Field Intelligence</p>
    </div>
    ${content}
    <p style="color:${BRAND_MUTED};font-size:11px;margin-top:32px;border-top:1px solid #e5e5e5;padding-top:16px;">
      This is an automated report generated by PnP Action Store Report.<br>
      Do not reply to this email.
    </p>
  </div>
</body>
</html>`.trim();
}

export interface StoreEmailParams {
  storeName: string;
  siteCode: string;
  rank: string;
  reportDate: string;
  repName: string;
  oosCount: number;
  phantomCount: number;
  missingCount: number;
  totalProducts: number;
  sohPositive: number;
  sohZeroOrNeg: number;
}

export function buildStoreEmail(params: StoreEmailParams): string {
  const {
    storeName, siteCode, rank, reportDate, repName,
    oosCount, phantomCount, missingCount,
    totalProducts, sohPositive, sohZeroOrNeg,
  } = params;

  const content = `
    <h2 style="color:${BRAND_CHARCOAL};margin-bottom:4px;">${storeName}</h2>
    <p style="color:${BRAND_MUTED};margin:0 0 4px;">
      Site Code: ${siteCode} &nbsp;|&nbsp; Rank: ${rank} &nbsp;|&nbsp; Date: ${reportDate}
    </p>
    <p style="margin-bottom:20px;">Hi ${repName},</p>
    <p style="margin-bottom:20px;">
      Please find attached the PnP Action Store Report for <strong>${storeName}</strong> as at ${reportDate}.
      Review the OOS, phantom stock, and missing SKU sheets and take the necessary action.
    </p>

    <table style="${tableStyle()}">
      <thead>
        <tr>
          <th style="${thStyle()}">Metric</th>
          <th style="${thStyle()}">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="${tdStyle(true)}">Total Products</td>
          <td style="${tdStyle(true)}"><strong>${totalProducts}</strong></td>
        </tr>
        <tr>
          <td style="${tdStyle(false)}">Products In Stock (SOH &gt; 0)</td>
          <td style="${tdStyle(false)}">${sohPositive}</td>
        </tr>
        <tr>
          <td style="${tdStyle(true)}">Products Out of Stock (SOH &le; 0)</td>
          <td style="${tdStyle(true)}"><span style="color:#ef4444;font-weight:bold;">${sohZeroOrNeg}</span></td>
        </tr>
        <tr>
          <td style="${tdStyle(false)}">Phantom Stock Lines</td>
          <td style="${tdStyle(false)}"><span style="color:#f59e0b;font-weight:bold;">${phantomCount}</span></td>
        </tr>
        <tr>
          <td style="${tdStyle(true)}">Missing SKUs</td>
          <td style="${tdStyle(true)}"><span style="color:#f59e0b;font-weight:bold;">${missingCount}</span></td>
        </tr>
      </tbody>
    </table>`;

  return wrapper(content);
}

export function buildSummaryEmail(
  reportDate: string,
  storesProcessed: number,
  emailsSent: number,
  spUploaded: number,
  errorCount: number
): string {
  const content = `
    <h2 style="color:${BRAND_CHARCOAL};margin-bottom:4px;">Processing Summary</h2>
    <p style="color:${BRAND_MUTED};margin:0 0 16px;">Report Date: ${reportDate}</p>
    <table style="${tableStyle()}">
      <thead>
        <tr>
          <th style="${thStyle()}">Metric</th>
          <th style="${thStyle()}">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr><td style="${tdStyle(true)}">Stores Processed</td><td style="${tdStyle(true)}"><strong>${storesProcessed}</strong></td></tr>
        <tr><td style="${tdStyle(false)}">Emails Sent</td><td style="${tdStyle(false)}">${emailsSent}</td></tr>
        <tr><td style="${tdStyle(true)}">SP Uploads</td><td style="${tdStyle(true)}">${spUploaded}</td></tr>
        <tr><td style="${tdStyle(false)}">Errors</td><td style="${tdStyle(false)}">${errorCount > 0 ? `<span style="color:#ef4444;">${errorCount}</span>` : '0'}</td></tr>
      </tbody>
    </table>`;

  return wrapper(content);
}
